# Generated by Django 5.0.3 on 2024-03-28 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_post_author_alter_post_content_and_more'),
        ('Profile', '0006_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profile.profile'),
        ),
    ]
