# Generated by Django 5.0.3 on 2024-03-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
