# Generated by Django 5.0.3 on 2024-03-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(height_field=50, null=True, upload_to='', width_field=50),
        ),
    ]
